In [2]:
import numpy as np

np.eye(10)

# generates a 10 by 10 identity matrix 

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [32]:
import numpy as np 

np.random.random()

# Generates a random real number in [0,1] (uniform distribution)

x=np.random.random((2,3))

x

# Generates a random 2 by 3 matrix with entries in [0,1]

np.random.randn()

# Generates random real numbers in accordance with the Gaussian distribution 

np.random.randn(2,3)

# Generates a 2 by 3 random matrix in accordance with the Gaussian distribution. Note the difference in syntax with 
# the uniform case. 

array([[ 0.76347269, -0.05186618, -1.99533486],
       [ 2.20976895,  1.05320078,  0.59709356]])

In [55]:
# Statistics of random distributions 

R=np.random.randn(10000)

# Generates 10000 random real numbers in accordance with Gauss distribution. 

R.mean()

# Computes the mean of R. It should be close to 0. 

R.std()

# Compuutes the standard deviation of R. 

R.var()

# Computes the variance of R. 

S=np.random.randn(10000,3)

# Generates 10000 random 3-vectors in accordance with the Gaussian distribution 

S.mean(axis=0)

# Computes the mean of each of the three columns. 

S.mean(axis=1)

# computes the mean across each row. 

np.cov(S.T)

# Computes the covariance matrix (note the need to take a transpose)

np.cov(S, rowvar=False)

# Accomplishes the same thing. 

array([[ 1.01841435,  0.01580427,  0.01808406],
       [ 0.01580427,  0.96385554, -0.01482662],
       [ 0.01808406, -0.01482662,  1.02184433]])

In [76]:
# Random integers 

np.random.randint(10)

# Generates a random integer between 0 and 10 (inclusive)

np.random.randint(-10,10)

# Generates a random integer between -10 and 10

np.random.randint(1,10,3)

# Generateas a random integer 3-vector with entries between 1 and 10. 

np.random.randint(0,10, size=(3,3))

# Generates a random 3 by 3 integer matrix with entries between 0 and 10 (inclusive)

X=[x for x in range(1,6)]
A=np.array(X)

np.random.choice(A, size=(2,2), p=[.2,.2,.3,.1,.2])

# This will require an in-depth discussion. This randomly selects a 2 by 2 matrix with entries in a given 
# array where each point in the array is chosen with some probability. 

array([[4, 5],
       [5, 3]])