In [23]:
# entering a matrix. Note that to run this cell, you must click on "Run" above. 

import numpy as np 

# numpy is the package needed to work with matrices in python effectively 

M=np.array([[1,2,5],[-1,2,7],[3,4,-10]])

# illustrates the syntax needed to input a matrix 

L=np.array([[1,0,0],[0,1,0],[0,0,1]])

# the 3 by 3 identity matrix 

X=M.dot(L)

X

# This multiplies two matrices together. Until you "call" K, python will not tell you what K is, so you must type: 

K 

# This will display K. If you comment out K, python will compute K=M*L, but will not display it. 

M+L

# This adds M and L.  







array([[  1,   2,   5],
       [ -1,   2,   7],
       [  3,   4, -10]])

In [11]:
# identifying elements of a matrix 

L=np.array([[1,0,0],[0,1,0],[0,0,1]])

# this is one of the matrices from above

L[0] 

# This will display the first row of the matrix L. Note that python counts from 0, not 1. 

L[0][1]

# This displays the second element of the first row. Once again, python begins its counter from 0, not 1. Note that
# if run this cell, python will execute the last operation listed, namely L[0][1]. If you want them both displyed, 
# you can do the following: 

a=L[0]

b=L[0][1]

a,b

(array([1, 0, 0]), 0)

In [13]:
# identifying elements of a matrix (continued)

M=np.array([[1,2,5],[-1,2,7],[3,4,-10]]) 

# This is one of the matrixes from above. 

M[:,0]

# This displays the first column 

M[:,2]

# This displayes the third column 





array([  5,   7, -10])

In [2]:
import numpy as np

# elementary operations on matrices

M=np.array([[1,2,5],[-1,2,7],[3,4,-10]]) 

M.T

# This takes a transpose of M

np.exp(M)

# This exponentiates every element of M 

M**2

# This squares every element of M. This DOES NOT multiply M by itself. 

(M.T)**2

# The process works quie well along with the transpose operation. 

np.linalg.det(M)

# Computes the determinant of M. 

U=np.array([[1,2,5],[-1,2,7],[3,4,-10]]) 

V=np.linalg.inv(U)

# Computes the inverse of M

#K=[[0,0,0],[1,2,3],[-1,0,1]]

#np.linalg.inv(K)

# You get an error message because the matrix is singular 

V.dot(U)

# Checks the inverse operations. Note that you do not quite get the identity matrix because of small errors that 
# accumulate!! 



array([[ 1.00000000e+00, -4.44089210e-16, -1.22124533e-15],
       [-2.77555756e-17,  1.00000000e+00,  2.77555756e-16],
       [ 2.08166817e-17,  2.77555756e-17,  1.00000000e+00]])

In [25]:
U=np.array([[1,2,5],[-1,2,7],[3,4,-10]]) 

U.shape[0]

3

In [6]:
import numpy as np

# trace function

U=np.array([[1,2,5],[-1,2,7],[3,4,-10]]) 

U[0][0]+U[1][1]+U[2][2]

# computes the trace of a matrix 

np.diag(U)

# Extracts the diagonal 

np.diag(U).sum()

# Sums up the elements of the diagonal, yielding the trace. 




-7

In [2]:
import numpy as np

# Eigenvalues and eigenvectors 

A=np.array([[1,0],[0,1]])

np.linalg.eig(A)

# Computes the eigenvalues and eigenvectors of A. 

Values, Vectors=np.linalg.eig(A)

print("The eigenvalues are: ", Values)

print("The eigenvectors are: ", Vectors)

# This way we separate the eigenvalues and eigenvectors are display them in a clear fashion. 

The eigenvalues are:  [1. 1.]
The eigenvectors are:  [[1. 0.]
 [0. 1.]]


In [5]:
# Checking if two vectors (or matrice)

a=np.array([1,2])
b=np.array([1,2+2**(-100)])
np.allclose(a,b)

True

Copyright (c) 2020 TRIPODS/GradStemForAll 2020 Team